[theme]
# Primary accent color for interactive elements.
primaryColor = "#1871d6"

# Background color for the main content area.
backgroundColor = "#ffffff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#76d472"

# Color used for almost all text.
textColor = "#000"
