[theme]
# Primary accent color for interactive elements.
primaryColor = "#8feb95"

# Background color for the main content area.
backgroundColor = "#3b4147"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#bf3045"

# Color used for almost all text.
textColor = "#fff"
